
## Lesson 2 - Creating Arrays: All Methods

Every creation method exists for a specific reason. Learn *when* to pick each one.

### 2.1 `np.array()` - Convert existing data
**When:** You already have a list, tuple, or nested structure.

In [2]:
import numpy as np

In [9]:
# 1D from list
a=np.array([1,2,3,4,5])
print('1D:', a)

# 2D from nested list -> used for matrices / feature tables
b=np.array([[1,2,3,4],[5,6,7,8]])
print('2D shape: ' , b.shape)
print('2D:', b)

# Force dtype - critical in ML (GPUs prefer float32, not float64)
c= np.array([1, 2, 3], dtype=np.float32)
print("dtype:", c.dtype)

# From tuple - same result as from list
d = np.array((10, 20, 30))
print("From tuple:", d)

1D: [1 2 3 4 5]
2D shape:  (2, 4)
2D: [[1 2 3 4]
 [5 6 7 8]]
dtype: float32
From tuple: [10 20 30]


### 2.2 `np.zeros()` / `np.ones()` / `np.full()` - Placeholder arrays
**When:** Initialising weight matrices, bias vectors, or output buffers before filling.

In [ ]:
# All zeros - default dtype is float64
z=np.zeros((4,4))
print("zeros:\n", z)

# All ones - used to initialise bias terms
o = np.ones((2, 3), dtype=np.float32)
print("\nones:\n", o)

# Fill with constant - used for padding (-1 for missing, 0 for images)
f = np.full((2, 4), fill_value=7)
print("\nfull(7):\n", f)

# zeros_like / ones_like - same shape as an existing array
x=np.array([[1,2],[3,4]])
print('\nzeroes_like:\n', np.zeros_like(x))
print('\nones_like:\n', np.ones_like(x))

zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

full(7):
 [[7 7 7 7]
 [7 7 7 7]]

zeroes_like:
 [[0 0]
 [0 0]]

ones_like:
 [[1 1]
 [1 1]]


### 2.3 `np.arange()` - Integer / step sequences
**When:** You need indices, loop-free ranges, or evenly spaced values.

In [27]:
print(np.arange(10))   #0..9
print(np.arange(0,1,0.1)) # float steps - unlike Python range()

print(np.arange(10,0,-2))  #reverse step

# Common use: batch indices in ML training
batch_size=32
indices=np.arange(1000)
print('\nFirst batch indice: ', indices[:batch_size])



[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[10  8  6  4  2]

First batch indice:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


### 2.4 `np.linspace()` - Evenly spaced floats (exact count)
**When:** Plotting, generating test inputs, learning rate schedules.
**Difference from arange:** You specify *how many* points, not the step size.

In [34]:
# 5 points between 0 and 1 inclusive
print(np.linspace(0,1,5))

# 100 points - perfect for plotting a smooth curve
x=np.linspace(-np.pi,np.pi,100)
print("sin values (first5): ", np.sin(x)[:5].round(3))

# endpoint=False - useful for periodic angles
angles=np.linspace(0,360,8,endpoint=False)
print("8 evenly spaced angles:", angles)



[0.   0.25 0.5  0.75 1.  ]
sin values (first5):  [-0.    -0.063 -0.127 -0.189 -0.251]
8 evenly spaced angles: [  0.  45.  90. 135. 180. 225. 270. 315.]


### 2.5 `np.eye()` - Identity matrix
**When:** Linear algebra, initialising transformation matrices, verifying matrix inverses.

In [62]:
# Student marks in 2 subjects
marks = np.array([[85, 90],
                  [78, 88]])

# Identity matrix
I = np.eye(2)

print("Student Marks:")
print(marks)

print("\nIdentity Matrix:")
print(I)

# Multiplying by the identity matrix
print("\nmarks @ I:")
print(marks @ I)

Student Marks:
[[85 90]
 [78 88]]

Identity Matrix:
[[1. 0.]
 [0. 1.]]

marks @ I:
[[85. 90.]
 [78. 88.]]


### 2.6 `np.random.*` - Random arrays
**When:** Initialising neural network weights, data augmentation, simulations, shuffling data.

In [81]:
# print(np.random.seed(45))

# Create a vector/matrix(by using reshape) of random numbers
print("random:\n", np.random.random(8).reshape(2,2,2))

# Uniform [0, 1) - used for dropout masks
print("rand:\n", np.random.rand(3,4).round(1))

# Random integers - class labels, batch sampling
print("\nrandint:", np.random.randint(0, 9, size=(3, 3)))

# Normal with custom mean and std
weights = np.random.normal(loc=0, scale=0.01, size=(128, 64))
print("\nWeight matrix shape:", weights.shape, " | mean:", weights.mean().round(5))

# Uniform with custom range
print("uniform:", np.random.uniform(1, 5, size=2).round(3))

random:
 [[[0.8112231  0.33424997]
  [0.47997266 0.57827256]]

 [[0.05920478 0.61729261]
  [0.53524647 0.5641738 ]]]
rand:
 [[0.5 0.8 0.  0.3]
 [0.8 0.2 0.6 0.1]
 [0.1 0.1 0.9 1. ]]

randint: [[8 1 6]
 [5 0 6]
 [3 3 3]]

Weight matrix shape: (128, 64)  | mean: -0.00011
uniform: [3.884 1.562]


### 2.7 `np.empty()` - Uninitialized array
**When:** Performance-critical code where you will fill every element immediately.
**Warning:** Values are garbage - never read before writing.

In [ ]:
# Fastest allocation - no initialisation overhead
buf=np.empty((1000,1000),dtype=float)
buf[:]=0 # fill immediately

print(buf)
print("Shape:", buf.shape, " dtype:", buf.dtype)



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Shape: (1000, 1000)  dtype: float64
8000128


### 2.8 `np.diag()` - Diagonal arrays
**When:** Covariance matrices, scaling transformations, extracting diagonals from matrices.

In [107]:
# Create diagonal matrix from values
D = np.diag([1, 2, 3, 4])
print("Diagonal matrix:\n", D)

# Extract diagonal from existing matrix
A=np.arange(9).reshape(3,3)
print('\nMatrix:\n', A)
print("Diagonal:", np.diag(A))



Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Diagonal: [0 4 8]


### 2.9 `np.fromfunction()` - Build array from a formula
**When:** Creating matrices whose values follow a mathematical formula.

In [110]:
# Multiplication table
mul_table = np.fromfunction(lambda i, j: (i+1)*(j+1), shape=(5, 5), dtype=int)
print("Multiplication table:\n", mul_table)

# Distance matrix - common in clustering algorithms
dist = np.fromfunction(lambda i, j: np.abs(i - j), shape=(4, 4), dtype=int)
print("\nDistance matrix:\n", dist)

Multiplication table:
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]

Distance matrix:
 [[0 1 2 3]
 [1 0 1 2]
 [2 1 0 1]
 [3 2 1 0]]


### 2.10 `np.loadtxt()` / `np.genfromtxt()` - Load from file
**When:** Reading CSV/TSV numerical datasets directly.

In [111]:
import io

# Simulate reading a CSV
csv_data = "1.0,2.0,3.0\n4.0,5.0,6.0\n7.0,8.0,9.0"
data = np.loadtxt(io.StringIO(csv_data), delimiter=",")
print("Loaded:\n", data)

# genfromtxt handles missing values
csv_missing = "1.0,2.0,\n4.0,,6.0"
data2 = np.genfromtxt(io.StringIO(csv_missing), delimiter=",", filling_values=0)
print("\nWith missing->0:\n", data2)

Loaded:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

With missing->0:
 [[1. 2. 0.]
 [4. 0. 6.]]
