## Lesson 4 - Indexing and Slicing

**The most-used skill in daily NumPy work.** Mastering this lets you extract any data without unnecessary copies.

In [1]:
import numpy as np

### 4.1 Basic Indexing - single elements

In [9]:
a=np.arange(24).reshape(4,6)
print("Array:\n",a)

print('\nRow 0              :',a[0])
print('Row 2, col 4       :',a[2,4])
print("Las Row            :",a[-1])
print("Las element        :",a[-1,-1])


Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Row 0              : [0 1 2 3 4 5]
Row 2, col 4       : 16
Las Row            : [18 19 20 21 22 23]
Las element        : 23


### 4.2 Slicing - ranges

In [28]:
a=np.arange(24).reshape(4,6)

print("Rows 1-2:\n", a[1:3])
print("\nAll rows, cols 2-4:\n", a[:, 2:5])
print("\nEvery other col:\n", a[:, ::2])
print("\nReverse cols:\n", a[:, ::-1])

# Train/Test split pattern

X=np.random.randn(100,10).round(2)

X_train=X[:80]
X_test=X[80:]
print("\nTrain:", X_train.shape, " | Test:", X_test.shape)



Rows 1-2:
 [[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

All rows, cols 2-4:
 [[ 2  3  4]
 [ 8  9 10]
 [14 15 16]
 [20 21 22]]

Every other col:
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]

Reverse cols:
 [[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]
 [17 16 15 14 13 12]
 [23 22 21 20 19 18]]

Train: (80, 10)  | Test: (20, 10)


### 4.3 Fancy (Integer) Indexing - arbitrary elements

In [41]:
a=np.array([10,20,30,40,50,60])

# Select specific indices - used for batch sampling
indices=np.array([0,2,4])
print('Fancy Index:',a[indices])

# 2D: pair-wise selection
A=np.arange(20).reshape(4,5)
print(A)
rows=np.array([0,1,2])
cols=np.array([0,1,2])

print('Pair-wise:', A[rows,cols])

# Mini-batch sampling
dataset=np.random.randn(1000,20).round(2)

batch_idx=np.random.choice(1000,size=32,replace=False)
mini_batch=dataset[batch_idx]
print("Mini-batch shape:", mini_batch.shape)



Fancy Index: [10 30 50]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Pair-wise: [ 0  6 12]
Mini-batch shape: (32, 20)


### 4.4 Boolean (Mask) Indexing - filter by condition

In [56]:
scores=np.array([72, 88, 45, 91, 67, 55, 95])
print('Passing(>=60)  :',scores[scores>=60])
print('60-90 range    :', scores[(scores>=60) & (scores <= 90)])

# Filter samples by class label
X=np.random.randn(100,4)
y=np.random.randint(0,3,size=100)
X_class0=X[y==0]
print("\nClass 0 samples:", X_class0.shape)

# Replace outliers - common in data cleaning
data=np.array([1.0, 200.0, 3.0, 4.0, 500.0])

# Left side ( what outlier to be replced) : right side (to replace with what )
data[data>100]=np.mean(data[data<=100])
print("After outlier fix:", data)



Passing(>=60)  : [72 88 91 67 95]
60-90 range    : [72 88 67]

Class 0 samples: (38, 4)
After outlier fix: [1.         2.66666667 3.         4.         2.66666667]


### 4.5 `np.where()` - Vectorised if-else
**When:** Conditional assignment, implementing activation functions, one-hot encoding.

In [61]:
a = np.array([-3, -1, 0, 2, 5, -4, 7])

# ReLU activation - the most common use of np.where
result = np.where(a > 0, a, 0)
print("ReLU output:", result)

# Find indices where condition is True
idx = np.where(a < 0)
print("Negative indices:", idx[0])

# One hot encoding
label=3
n_classes=5
one_hot=np.where(np.arange(n_classes)==label,1,0)
print("One-hot:", one_hot)



ReLU output: [0 0 0 2 5 0 7]
Negative indices: [0 1 5]
One-hot: [0 0 0 1 0]
