
## Lesson 6 - Math and Universal Functions (ufuncs)

**What:** Ufuncs operate element-wise on arrays at C speed.
**Why:** Replace Python loops entirely. Core of all vectorised ML math.

In [1]:
import numpy as np

### 6.1 Element-wise arithmetic

In [2]:
a = np.array([1., 2., 3., 4.])
b = np.array([10., 20., 30., 40.])

print("a + b :", a + b)
print("a - b :", a - b)
print("a * b :", a * b)      # element-wise, NOT matrix multiply
print("a / b :", a / b)
print("a ** 2:", a ** 2)
print("a % 3 :", a % 3)

# Scalar operations - broadcast automatically
print("\na * 5  :", a * 5)
print("a + 100:", a + 100)

a + b : [11. 22. 33. 44.]
a - b : [ -9. -18. -27. -36.]
a * b : [ 10.  40.  90. 160.]
a / b : [0.1 0.1 0.1 0.1]
a ** 2: [ 1.  4.  9. 16.]
a % 3 : [1. 2. 0. 1.]

a * 5  : [ 5. 10. 15. 20.]
a + 100: [101. 102. 103. 104.]


### 6.2 Common mathematical ufuncs
**Includes activation functions used every day in ML.**

In [ ]:
x=np.linspace(0,2*np.pi,5)

print("sin :", np.sin(x).round(3))
print("sin :", np.cos(x).round(3))
print("sin :", np.exp(x).round(3))
print("log :", np.log(np.array([1, np.e, np.e**2])).round(3))
print("sqrt:", np.sqrt(np.array([1, 4, 9, 16])))
print("abs :", np.abs(np.array([-3, -1, 0, 2])))

z = np.array([-2., -1., 0., 1., 2.])

# Activation Functions to introduce non_linearity in deeplearning NN
# Sigmoid
sigmoid=1/(1+np.exp(z))
print("\nSigmoid:", sigmoid.round(3))

# ReLU
relu = np.maximum(0, z)
print("ReLU   :", relu)

# Softmax (with numerical stability trick)
def softmax(x):
    e = np.exp(x - x.max())   # subtract max to prevent overflow
    return e / e.sum()

logits = np.array([2.0, 1.0, 0.1])
print("Softmax:", softmax(logits).round(3), " | sum:", softmax(logits).sum())


sin : [ 0.  1.  0. -1. -0.]
sin : [ 1.  0. -1. -0.  1.]
sin : [  1.      4.81   23.141 111.318 535.492]
log : [0. 1. 2.]
sqrt: [1. 2. 3. 4.]
abs : [3 1 0 2]

Sigmoid: [0.881 0.731 0.5   0.269 0.119]
ReLU   : [0. 0. 0. 1. 2.]
Softmax: [0.659 0.242 0.099]  | sum: 1.0


### 6.3 Matrix multiplication - the core of ML

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Element-wise A*B:\n", A * B)      # NOT matrix multiply

# Matrix multiplication - 3 equivalent ways
print("\nA @ B:\n",          A @ B) 
print("np.dot(A,B):\n",    np.dot(A, B))
print("np.matmul(A,B):\n", np.matmul(A, B))

# Full forward pass of one neural layer
np.random.seed(0)
batch_size,n_in,n_out=32,128,64 

X=np.random.randn(batch_size,n_in)
W=np.random.randn(n_in,n_out) *0.01
print("length",(W))
b=np.zeros(n_out)

Z = X @ W + b                      # linear transformation
A_out = np.maximum(0, Z)   #Relue

print("\nNeural layer forward pass:")
print("  X:", X.shape, " W:", W.shape, " b:", b.shape)
print("  Z:", Z.shape, " A:", A_out.shape)


Element-wise A*B:
 [[ 5 12]
 [21 32]]

A @ B:
 [[19 22]
 [43 50]]
np.dot(A,B):
 [[19 22]
 [43 50]]
np.matmul(A,B):
 [[19 22]
 [43 50]]
length [[ 0.01629475 -0.00099045 -0.00201992 ... -0.01178944  0.00029122
   0.00559548]
 [ 0.00881037  0.00715208 -0.00462078 ... -0.00594332 -0.00055439
   0.00796561]
 [ 0.0013318  -0.00541678 -0.00865302 ... -0.01592195 -0.0142595
  -0.00491552]
 ...
 [-0.00223014 -0.00756481 -0.00091613 ...  0.0076067  -0.02603613
   0.00231241]
 [ 0.00062179  0.01317423 -0.00590032 ...  0.00488113 -0.00170269
  -0.01169091]
 [-0.01826187 -0.00423037  0.00478851 ...  0.00509159 -0.00158269
   0.00691676]]

Neural layer forward pass:
  X: (32, 128)  W: (128, 64)  b: (64,)
  Z: (32, 64)  A: (32, 64)
