## Lesson 5 - Reshaping and Manipulation

**Why:** In ML/DL, data shape must match what each layer or function expects. You reshape constantly.

In [1]:
import numpy as np

### 5.1 `reshape()` - Change shape, keep data

In [14]:
a=np.arange(24)
print("Original shape:", a.shape)

b=a.reshape(4,6)
print("4x6: ", b.shape)

c = a.reshape(2, 3, 4)
print("\n2x3x4:", c.shape)

# -1 means infer this dimension ( let numpy to figure out dimention(-1))
d = a.reshape(-1, 6)
print("-1x6:", d.shape)

# Flatten batch of images
batch_images=np.random.rand(32,28,28)
flat=batch_images.reshape(32,-1)
print("\nImages:", batch_images.shape, "-> flat:", flat.shape)




Original shape: (24,)
4x6:  (4, 6)

2x3x4: (2, 3, 4)
-1x6: (4, 6)

Images: (32, 28, 28) -> flat: (32, 784)


### 5.2 `flatten()` vs `ravel()` - Collapse to 1D

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])

flat=a.flatten()  # always returns a COPY
rav=a.ravel()     # returns a VIEW when possible (faster)tries to reuse same memory

print("flatten:", flat)
print("ravel  :", rav)

# Prove ravel is a view - modifying it changes original
rav[0]=999
print("Original[0,0] after modifying ravel:", a[0, 0])





flatten: [1 2 3 4 5 6]
ravel  : [1 2 3 4 5 6]
Original[0,0] after modifying ravel: 999


### 5.3 `expand_dims()` / `squeeze()` - Add or remove size-1 axes
**When:** Preparing single inputs for batch-expecting models, cleaning up shapes.

In [46]:
a = np.array([1, 2, 3])   # shape (3,)

# Add axis - make (1, 3) row vector
row=np.expand_dims(a,axis=0)
print("axis=0:", row.shape)

# Add axis - make (3, 1) column vector
col=np.expand_dims(a,axis=1)
print("axis=1:", col.shape)

# np.newaxis is the same as None - more readable inline
print("newaxis row:", a[np.newaxis, :].shape)
print("newaxis col:", a[:, np.newaxis].shape)


# squeeze - remove all size-1 dimensions
b= np.array([[[1,2,3]]])
print("\nsqueeze:", np.squeeze(b).shape)    # -> (3,)


# DL pattern: single image for prediction
image=np.random.rand(224,224,3)
batch=np.expand_dims(image,axis=0)
print("\nSingle image:", image.shape, "-> batch:", batch.shape)


axis=0: (1, 3)
axis=1: (3, 1)
newaxis row: (1, 3)
newaxis col: (3, 1)

squeeze: (3,)

Single image: (224, 224, 3) -> batch: (1, 224, 224, 3)


### 5.4 Combining arrays

In [57]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("concatenate axis=0 (rows):\n", np.concatenate([a, b], axis=0))
print("\nconcatenate axis=1 (cols):\n", np.concatenate([a, b], axis=1))

print("\nvstack:\n", np.vstack([a, b]))
print("\nhstack:\n", np.hstack([a, b]))

# np.stack - creates a NEW axis
c = np.stack([a, b], axis=0)
print("\nstack shape:", c.shape)

# Build a feature matrix from separate arrays
age=np.array([20,25,30])[:, np.newaxis]
salary=np.array([2000,2500,3000])[:, np.newaxis]
record=np.hstack([age,salary])
print("\nFeature matrix:\n",record)




concatenate axis=0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1 (cols):
 [[1 2 5 6]
 [3 4 7 8]]

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
 [[1 2 5 6]
 [3 4 7 8]]

stack shape: (2, 2, 2)

Feature matrix:
 [[  20 2000]
 [  25 2500]
 [  30 3000]]


### 5.5 Splitting arrays

In [68]:
a = np.arange(12).reshape(3,4)
print("Original\n" ,a)

left , right = np.hsplit(a,2)
print("\nLeft:\n", left)
print("Right:\n", right)

top, bottom = np.vsplit(a, [2])
print("\nTop:\n", top)
print("Bottom:\n", bottom)

parts = np.split(np.arange(10), [3, 7])
print("\nSplit into parts:", parts)

Original
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Left:
 [[0 1]
 [4 5]
 [8 9]]
Right:
 [[ 2  3]
 [ 6  7]
 [10 11]]

Top:
 [[0 1 2 3]
 [4 5 6 7]]
Bottom:
 [[ 8  9 10 11]]

Split into parts: [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


### 5.6 Transpose and axis manipulation

In [124]:
a = np.arange(24).reshape(2, 3, 4)
print("Original shape:", a.shape)
print("Transposed    :", a.T.shape)

img_tf = np.random.rand(28, 28, 3)
img_pt = np.transpose(img_tf, (2, 0, 1))
print("\nTF format:", img_tf.shape, "-> PyTorch:", img_pt.shape)

# swapaxes
b = np.arange(6).reshape(2, 3)
print("\nOriginal:\n", b)
print("swapaxes(0,1):\n", np.swapaxes(b, 0, 1))

Original shape: (2, 3, 4)
Transposed    : (4, 3, 2)

TF format: (28, 28, 3) -> PyTorch: (3, 28, 28)

Original:
 [[0 1 2]
 [3 4 5]]
swapaxes(0,1):
 [[0 3]
 [1 4]
 [2 5]]
